export const ACTIVE_LOADING = 'ACTIVE_LOADING'
export const DISABLED_LOADING = 'DISABLED_LOADING'

export const GET_DOGS = 'GET_DOGS'
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS'

export const PAGE_CHANGE = 'PAGE_CHANGE'
export const DOG_NAME_CHANGE = 'DOG_NAME_CHANGE'
export const TEMPERAMENT_NAME_CHANGE = 'TEMPERAMENT_NAME_CHANGE'

export const ORIGIN_FILTER = 'ORIGIN_FILTER'
export const RESET_FILTER = 'RESET_FILTER'